version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test-spring
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test-spring
      MYSQL_USER: beto
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro 

volumes:
  mysql-data:
